### ISSUE TITLE
mmol/l

### ISSUE THREAD

**Issue by quotengrote** [ThielHater/Trayscout#1]
Hi, thx for your app.

Is it possible to show the Values in mmol/l instead of mg/dl?

Wishes
mg

**Comment by ThielHater** [comment]
Hi Michael, I thought the code to be unit agnostic although I have to admit that I didn't test mmol/L so far. It seems like the API of Nightsout always returns mg/dl, no matter if DISPLAY_UNITS is set to mmol/L. Well, then I will introduce a parameter for this in Trayscout. Give me a few days.

**Comment by quotengrote** [comment]
Hi,

that would be great, thanks.

Have a nice christmas
mg

**Comment by ThielHater** [comment]
This was implemented with commit 0925f70f2062bce48b3acd5b9612205284032111, please download [latest release](https://github.com/ThielHater/Trayscout/releases/tag/1.4).

**Comment by quotengrote** [comment]
Thx, works great.
