### ISSUE TITLE
mmolL

### ISSUE THREAD

**Issue by alfureu** [ThielHater/Trayscout#2]
When switched to mmolL 3-digit results, e.g. 10.0 or higher are missing the leading character, so it shows as 0.0. Could you please fix, or provide an option to make the font smaller? 

I would even consider removing the ▶ sign as well to make the result more visible in the tray

**Comment by ThielHater** [comment]
Good catch, this should have popped up earlier. The icon in the system tray is 16\*16px and the value is drawn using a bitmap font I created with each symbol being 5\*8px. This makes good use of the available space and is always sharp. I had tried different vector fonts before but the result was blurry and not consistent.

As a quickfix, values above 10.0 are now rounded, you may download the latest version. Removing the trend indicator is not an option to me. I guess the best solution would be to create a new font with each symbol being 4\*8px.

**Comment by alfureu** [comment]
Thanks for the quick info, tbh, the new rounded font is not ideal. I found this as a 4x8px font https://fontstruct.com/fontstructions/show/590047/px_4x8. I know, it does not have the special signs for trend tho... I know this is a pain in the bottom, but I am looking around for a usable indicator for NS, so far all of them have their quirks... 

And at the same time, there are apps like HDD Sentinel (app for monitoring hard drive temperature), which somehow manage to render the fonts. Maybe this could be an inspiration: 

![image](https://user-images.githubusercontent.com/10846169/150947016-852ff568-1fd2-4fef-a662-5f1470045d43.png)

i.e. put the number into the square and the trend can be somehow a coloured "background" maybe? One can even play around with the trend indicator to highlight different corners of the square for that. Just trying to play around with the idea...

**Comment by ThielHater** [comment]
As the saying goes, well meant is not well done. TrayScout already uses its own font, which technically works differently from the one you linked. I don't see what HDD Sentinel does better, displaying two digits is not the problem. What does it do with four? And lastly, I don't think it's a good idea to break the experience of all other users and completely change the style.

**Comment by ThielHater** [comment]
I took the time to adjust the font and make the drawing procedure a little smarter (9c5278b16ac442ab262afcebfca1c707dbaf73da). It should look the same for almost all values and display four-digit values properly.
